# Generated by Django 2.0.1 on 2018-08-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_courseorg_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '类型', 'verbose_name_plural': '类型'},
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='age',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='work_position',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='work_years',
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='address',
            field=models.CharField(max_length=150, verbose_name='知识信息'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('ew', '易维公司'), ('hz', '合作伙伴'), ('ss', '水司')], default='pxjg', max_length=20, verbose_name='分类类别'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(default='产品信息', max_length=10, verbose_name='分类标签'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=50, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='org',
            field=models.CharField(max_length=50, verbose_name='销售阶段'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='points',
            field=models.CharField(max_length=50, verbose_name='特点'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='work_company',
            field=models.CharField(max_length=50, verbose_name='产品来源'),
        ),
    ]
