# Generated by Django 2.0.1 on 2018-08-12 21:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20180812_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=18, verbose_name='用户数'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='work_position',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='产品定位'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='work_years',
            field=models.IntegerField(default=0, verbose_name='f发布年限'),
        ),
    ]
