# Generated by Django 2.0.1 on 2018-08-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_auto_20180822_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.CharField(default='1@ewide.net', max_length=50, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='address',
            field=models.CharField(max_length=1050, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(choices=[('A', 'A新兵营'), ('B', 'B十八般兵器'), ('C', 'C货好不难卖'), ('D', 'D武功密籍'), ('E', 'E江湖风云录')], max_length=10, verbose_name='类型标签'),
        ),
    ]
