# Generated by Django 2.0.1 on 2019-12-06 16:00

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='smartpipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caliber', models.CharField(blank=True, max_length=10, null=True, verbose_name='口径')),
                ('sn', models.CharField(blank=True, max_length=40, null=True, verbose_name='编号')),
                ('label', models.CharField(blank=True, max_length=60, null=True, verbose_name='电子标签')),
                ('vendor_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='供应商')),
                ('profile_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='消息名称')),
                ('profile_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='消息类型')),
                ('broker_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='消息ip')),
                ('broker_port', models.IntegerField(blank=True, default=0, null=True, verbose_name='端口')),
                ('client_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='客户端ID')),
                ('conn_timeout', models.IntegerField(blank=True, default=0, null=True, verbose_name='连接timeout')),
                ('MQTT_version', models.CharField(blank=True, max_length=40, null=True, verbose_name='MQTT版本')),
                ('profile_version', models.CharField(blank=True, max_length=40, null=True, verbose_name='协议版本')),
                ('publish_item', models.CharField(blank=True, max_length=100, null=True, verbose_name='发布信息项')),
                ('msg_sec', models.IntegerField(blank=True, default=0, null=True, verbose_name='发布时间间隔')),
                ('collection_min', models.IntegerField(blank=True, default=0, null=True, verbose_name='采集时间间隔')),
                ('po_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='订单时间')),
                ('check_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='检验时间')),
                ('check_file', models.CharField(blank=True, max_length=100, null=True, verbose_name='检验报告')),
                ('check_spec', DjangoUeditor.models.UEditorField(blank=True, default='', null=True, verbose_name='标定数据')),
                ('factory_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='出厂时间')),
                ('arrival_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='到货时间')),
                ('owner_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='业主编号')),
                ('project_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='项目编号')),
                ('RTU_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='RTU编号')),
                ('depth', models.IntegerField(blank=True, default=0, null=True, verbose_name='埋深')),
                ('install_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='安装时间')),
                ('interface', models.CharField(blank=True, max_length=30, null=True, verbose_name='接口方式')),
                ('pipeline', models.CharField(blank=True, max_length=30, null=True, verbose_name='管道材质')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='安装经度')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='安装纬度')),
                ('cancel_flag', models.IntegerField(blank=True, default=0, null=True, verbose_name='是否报废')),
                ('pressure_low', models.FloatField(blank=True, null=True, verbose_name='压力报警低限')),
                ('pressure_high', models.FloatField(blank=True, null=True, verbose_name='压力告警高限')),
                ('power_low', models.FloatField(blank=True, null=True, verbose_name='电力告警低限')),
                ('flow_l', models.CharField(blank=True, max_length=128, null=True, verbose_name='分析告警')),
            ],
            options={
                'verbose_name': '智慧管件',
                'verbose_name_plural': '智慧管件',
            },
        ),
    ]
