# Generated by Django 2.0.1 on 2019-12-09 14:09

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartpipe',
            name='accident_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='处理完成时间'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='accident_hand',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='工单处理情况描述'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='accident_pic',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='工单处理图片上传'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='accident_result',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='处理结果（已完成、取消、未完成）'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='accident_star',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='处理评级（1星—5星）'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='alert_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='告警时间'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='alert_hand',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', null=True, verbose_name='详细描述'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='alert_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='关联告警事务                         '),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='alert_result',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='告警解决情况（已完成、取消、未完成）'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='alert_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='告警类型'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='collection_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='采集时间'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='concact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='联系人'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='contract',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='联系人'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='design_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='编号'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='info',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', null=True, verbose_name='设计院信息'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='ins_flow',
            field=models.FloatField(blank=True, null=True, verbose_name='瞬间流量'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='msg_info',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='消息内容'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='msg_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='消息时间'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='order_p',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='安排人员'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='phone_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='手机'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='pipe_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='关联管件'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='po_info',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='订单描述'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='power',
            field=models.FloatField(blank=True, null=True, verbose_name='电力情况'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='压力'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='reason',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='告警依据'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='reg_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='注册时间'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='tot_flow',
            field=models.FloatField(blank=True, null=True, verbose_name='累计流量'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='turnup_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='到场时间'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='turnup_lat',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='到场打卡纬度'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='turnup_lon',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='到场打卡经度'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='wx',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='微信名'),
        ),
        migrations.AlterField(
            model_name='smartpipe',
            name='latitude',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='维度'),
        ),
        migrations.AlterField(
            model_name='smartpipe',
            name='longitude',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='smartpipe',
            name='owner_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='业主编号'),
        ),
        migrations.AlterField(
            model_name='smartpipe',
            name='project_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='smartpipe',
            name='vendor_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='编号'),
        ),
    ]
