# Generated by Django 2.0.1 on 2019-12-09 15:05

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpipe', '0003_auto_20191209_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='告警类型')),
                ('pipe_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='关联管件')),
                ('reason', models.CharField(blank=True, max_length=500, null=True, verbose_name='告警依据')),
                ('alert_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='告警时间')),
                ('alert_hand', DjangoUeditor.models.UEditorField(blank=True, default='', null=True, verbose_name='详细描述')),
                ('alert_result', models.CharField(blank=True, max_length=50, null=True, verbose_name='告警解决情况（已完成、取消、未完成）')),
            ],
            options={
                'verbose_name': '自动告警',
                'verbose_name_plural': '自动告警',
            },
        ),
        migrations.CreateModel(
            name='design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='编号')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='名称')),
                ('info', DjangoUeditor.models.UEditorField(blank=True, default='', null=True, verbose_name='设计院信息')),
                ('contract', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系人')),
                ('phone_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='手机')),
                ('wx', models.CharField(blank=True, max_length=100, null=True, verbose_name='微信名')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='email')),
                ('reg_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='注册时间')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='地址')),
                ('longitude', models.CharField(blank=True, max_length=40, null=True, verbose_name='经度')),
                ('latitude', models.CharField(blank=True, max_length=40, null=True, verbose_name='维度')),
            ],
            options={
                'verbose_name': '设计院',
                'verbose_name_plural': '设计院',
            },
        ),
        migrations.CreateModel(
            name='mqttmsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='消息名称')),
                ('profile_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='消息类型')),
                ('broker_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='消息ip')),
                ('broker_port', models.IntegerField(blank=True, default=0, null=True, verbose_name='端口')),
                ('client_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='客户端ID')),
                ('msg_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='消息时间')),
                ('msg_info', models.CharField(blank=True, max_length=500, null=True, verbose_name='消息内容')),
            ],
            options={
                'verbose_name': 'MQTT消息明细',
                'verbose_name_plural': 'MQTT消息明细',
            },
        ),
        migrations.CreateModel(
            name='owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='编号')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='名称')),
                ('info', models.CharField(blank=True, max_length=500, null=True, verbose_name='业主信息')),
                ('concact', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系人')),
                ('phone_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='手机')),
                ('wx', models.CharField(blank=True, max_length=100, null=True, verbose_name='微信名')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='email')),
                ('reg_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='注册时间')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='地址')),
                ('longitude', models.CharField(blank=True, max_length=40, null=True, verbose_name='经度')),
                ('latitude', models.CharField(blank=True, max_length=40, null=True, verbose_name='维度')),
            ],
            options={
                'verbose_name': '业主信息',
                'verbose_name_plural': '业主信息',
            },
        ),
        migrations.CreateModel(
            name='pipedetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipe_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='管件编号')),
                ('collection_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='采集时间')),
                ('pressure', models.FloatField(blank=True, null=True, verbose_name='压力')),
                ('ins_flow', models.FloatField(blank=True, null=True, verbose_name='瞬间流量')),
                ('tot_flow', models.FloatField(blank=True, null=True, verbose_name='累计流量')),
                ('power', models.FloatField(blank=True, null=True, verbose_name='电力情况')),
            ],
            options={
                'verbose_name': '管件使用明细',
                'verbose_name_plural': '管件使用明细',
            },
        ),
        migrations.CreateModel(
            name='po',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='编号')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='名称')),
                ('info', models.CharField(blank=True, max_length=500, null=True, verbose_name='业主信息')),
                ('concact', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系人')),
                ('phone_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='手机')),
                ('wx', models.CharField(blank=True, max_length=100, null=True, verbose_name='微信名')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='email')),
                ('po_info', models.CharField(blank=True, max_length=500, null=True, verbose_name='订单描述')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
            },
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='编号')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='名称')),
                ('owner_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='业主编号')),
                ('info', DjangoUeditor.models.UEditorField(blank=True, default='', null=True, verbose_name='项目信息')),
                ('contract', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系人')),
                ('phone_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='手机')),
                ('wx', models.CharField(blank=True, max_length=100, null=True, verbose_name='微信名')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='email')),
                ('reg_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='注册时间')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='地址')),
                ('longitude', models.CharField(blank=True, max_length=40, null=True, verbose_name='经度')),
                ('latitude', models.CharField(blank=True, max_length=40, null=True, verbose_name='维度')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='编号')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='名称')),
                ('info', DjangoUeditor.models.UEditorField(blank=True, default='', null=True, verbose_name='供应商信息')),
                ('contract', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系人')),
                ('phone_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='手机')),
                ('wx', models.CharField(blank=True, max_length=100, null=True, verbose_name='微信名')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='email')),
                ('reg_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='注册时间')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='地址')),
                ('longitude', models.CharField(blank=True, max_length=40, null=True, verbose_name='经度')),
                ('latitude', models.CharField(blank=True, max_length=40, null=True, verbose_name='维度')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
            },
        ),
        migrations.CreateModel(
            name='workorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipe_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='管件编号')),
                ('reason', models.CharField(blank=True, max_length=500, null=True, verbose_name='派单原因（巡检、事故维修、更换）')),
                ('alert_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='关联告警事务                         ')),
                ('order_p', models.CharField(blank=True, max_length=40, null=True, verbose_name='安排人员')),
                ('turnup_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='到场时间')),
                ('turnup_lon', models.CharField(blank=True, max_length=40, null=True, verbose_name='到场打卡经度')),
                ('turnup_lat', models.CharField(blank=True, max_length=40, null=True, verbose_name='到场打卡纬度')),
                ('accident_hand', models.CharField(blank=True, max_length=500, null=True, verbose_name='工单处理情况描述')),
                ('accident_pic', models.CharField(blank=True, max_length=200, null=True, verbose_name='工单处理图片上传')),
                ('accident_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='处理完成时间')),
                ('accident_result', models.CharField(blank=True, max_length=50, null=True, verbose_name='处理结果（已完成、取消、未完成）')),
                ('accident_star', models.CharField(blank=True, max_length=50, null=True, verbose_name='处理评级（1星—5星）')),
            ],
            options={
                'verbose_name': '管件运维工单明细',
                'verbose_name_plural': '管件运维工单明细',
            },
        ),
        migrations.AlterModelOptions(
            name='smartpipe',
            options={'verbose_name': '智慧管件', 'verbose_name_plural': '智慧管件'},
        ),
        migrations.RenameField(
            model_name='smartpipe',
            old_name='design_id',
            new_name='sn',
        ),
        migrations.RemoveField(
            model_name='smartpipe',
            name='address',
        ),
        migrations.RemoveField(
            model_name='smartpipe',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='smartpipe',
            name='email',
        ),
        migrations.RemoveField(
            model_name='smartpipe',
            name='info',
        ),
        migrations.RemoveField(
            model_name='smartpipe',
            name='name',
        ),
        migrations.RemoveField(
            model_name='smartpipe',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='smartpipe',
            name='reg_date',
        ),
        migrations.RemoveField(
            model_name='smartpipe',
            name='wx',
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='MQTT_version',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='MQTT版本'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='RTU_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='RTU编号'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='arrival_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='到货时间'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='broker_address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='消息ip'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='broker_port',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='端口'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='caliber',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='口径'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='cancel_flag',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='是否报废'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='check_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='检验时间'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='check_file',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='检验报告'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='check_spec',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', null=True, verbose_name='标定数据'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='client_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='客户端ID'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='collection_min',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='采集时间间隔'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='conn_timeout',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='连接timeout'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='depth',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='埋深'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='factory_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='出厂时间'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='flow_l',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='分析告警'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='install_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='安装时间'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='interface',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='接口方式'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='label',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='电子标签'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='msg_sec',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='发布时间间隔'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='owner_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='业主编号'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='pipeline',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='管道材质'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='po_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='订单时间'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='power_low',
            field=models.FloatField(blank=True, null=True, verbose_name='电力告警低限'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='pressure_high',
            field=models.FloatField(blank=True, null=True, verbose_name='压力告警高限'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='pressure_low',
            field=models.FloatField(blank=True, null=True, verbose_name='压力报警低限'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='profile_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='消息名称'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='profile_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='消息类型'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='profile_version',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='协议版本'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='project_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='项目编号'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='publish_item',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='发布信息项'),
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='vendor_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='供应商'),
        ),
        migrations.AlterField(
            model_name='smartpipe',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='安装纬度'),
        ),
        migrations.AlterField(
            model_name='smartpipe',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='安装经度'),
        ),
    ]
