# Generated by Django 2.0.1 on 2019-12-09 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartpipe', '0004_auto_20191209_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mqttmsg',
            old_name='profile_name',
            new_name='name',
        ),
    ]
