# Generated by Django 2.0.1 on 2019-12-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpipe', '0006_auto_20191209_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipedetail',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='消息名称'),
        ),
    ]
