# Generated by Django 2.0.1 on 2019-12-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpipe', '0007_pipedetail_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='latitude',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='纬度'),
        ),
    ]
