# Generated by Django 2.0.1 on 2019-12-11 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smartpipe', '0008_auto_20191211_0944'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mqttmsg',
        ),
        migrations.DeleteModel(
            name='owner',
        ),
        migrations.DeleteModel(
            name='po',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='alert_type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='workorder',
            old_name='reason',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner_id',
        ),
        migrations.RemoveField(
            model_name='smartpipe',
            name='RTU_id',
        ),
        migrations.RemoveField(
            model_name='smartpipe',
            name='cancel_flag',
        ),
        migrations.RemoveField(
            model_name='smartpipe',
            name='owner_id',
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='pipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartpipe.smartpipe', verbose_name='管件编号'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='pipe_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartpipe.smartpipe', verbose_name='管件编号'),
        ),
    ]
