# Generated by Django 2.0.1 on 2019-12-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpipe', '0010_auto_20191211_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartpipe',
            name='profile_name',
        ),
        migrations.AddField(
            model_name='smartpipe',
            name='profile消息名称_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='消息名称'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='名称'),
        ),
    ]
