# Generated by Django 2.0.1 on 2019-12-20 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartpipe', '0011_auto_20191220_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartpipe',
            old_name='profile消息名称_name',
            new_name='profile_name',
        ),
    ]
