# Generated by Django 2.0.1 on 2019-12-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpipe', '0012_auto_20191220_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipedetail',
            name='tem',
            field=models.FloatField(blank=True, null=True, verbose_name='温度'),
        ),
    ]
