# Generated by Django 2.0.1 on 2020-02-16 15:47

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartpipe', '0013_pipedetail_tem'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='geometry',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', null=True, verbose_name='地理数据'),
        ),
    ]
