# Generated by Django 2.0.1 on 2018-10-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecomments',
            name='kind',
            field=models.CharField(choices=[('fk', '交流'), ('zx', '咨询'), ('jy', '建议')], default='fk', max_length=2, verbose_name='类型'),
        ),
    ]
