# Generated by Django 2.0.1 on 2018-10-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20181010_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecomments',
            name='ctitle',
            field=models.CharField(default='交流', max_length=30, verbose_name='主题'),
        ),
        migrations.AlterField(
            model_name='coursecomments',
            name='kind',
            field=models.CharField(choices=[('pl', '好评'), ('cp', '差评'), ('zx', '咨询'), ('jl', '交流')], default='pl', max_length=2, verbose_name='类型'),
        ),
    ]
