# Generated by Django 2.0.1 on 2018-10-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_auto_20181012_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecomments',
            name='comments',
            field=models.CharField(max_length=250, verbose_name='交流'),
        ),
    ]
