# Generated by Django 2.0.1 on 2018-10-12 18:11

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_auto_20181012_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecomments',
            name='comments',
            field=mdeditor.fields.MDTextField(verbose_name='交流'),
        ),
    ]
