# Generated by Django 2.0.1 on 2018-12-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ewProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.CharField(max_length=24, verbose_name='任务单编号')),
                ('p_month', models.CharField(max_length=10, verbose_name='月份')),
                ('name', models.CharField(max_length=128, verbose_name='项目名称')),
                ('p_dept', models.CharField(max_length=40, verbose_name='所属部门')),
                ('p_org', models.CharField(max_length=40, verbose_name='大类')),
                ('p_type', models.CharField(max_length=40, verbose_name='分项')),
                ('p_kind', models.CharField(max_length=40, verbose_name='分类')),
                ('p_money', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='合同金额')),
                ('p_back_m', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='已回款金额')),
                ('p_back_scale', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='回款比例')),
                ('p_m1', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='首付款')),
                ('p_m2', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='启动款')),
                ('p_m3', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='上线款')),
                ('p_m4', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='验收款')),
                ('p_m5', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='质保款')),
                ('p_task_m', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='软件实施费')),
                ('p_project_m', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='人工差旅费')),
                ('p_project_scale', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='已发生费比例')),
            ],
            options={
                'verbose_name': '项目监管',
                'verbose_name_plural': '项目监管',
            },
        ),
    ]
