# Generated by Django 2.0.1 on 2018-12-13 16:24

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewproject', '0002_ewproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='ewproject',
            name='area_rank',
            field=models.CharField(default='市', max_length=20, verbose_name='级别'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='bargain_id',
            field=models.CharField(max_length=30, null=True, verbose_name='系统合同编号'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='bargain_m',
            field=models.DecimalField(decimal_places=0, max_digits=12, null=True, verbose_name='合同总金额'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='bargain_memo',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='合同内容描述'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='builder_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='创建日期'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='c_budget_m',
            field=models.DecimalField(decimal_places=0, max_digits=12, null=True, verbose_name='预算'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='c_cash_cost',
            field=models.DecimalField(decimal_places=0, max_digits=12, null=True, verbose_name='资金成本'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='c_chk_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='实际验收日期'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='c_chk_man',
            field=models.CharField(max_length=200, null=True, verbose_name='验收参与人员'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='c_code_backup_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='代码备份时间'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='c_database_backup_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='数据库备份时间'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='c_diff_m',
            field=models.DecimalField(decimal_places=0, max_digits=12, null=True, verbose_name='预决算盈亏'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='c_file_audit_c',
            field=models.DecimalField(decimal_places=0, max_digits=12, null=True, verbose_name='检视表要求文档数'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='c_file_memo',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='文档检视明细'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='c_filechklist_c',
            field=models.DecimalField(decimal_places=0, max_digits=12, null=True, verbose_name='检视表要求文档数'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='c_final_m',
            field=models.DecimalField(decimal_places=0, max_digits=12, null=True, verbose_name='决算'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='c_pay_cost',
            field=models.DecimalField(decimal_places=0, max_digits=12, null=True, verbose_name='采购成本'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='c_use_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='实际上线日期'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='c_week',
            field=models.DecimalField(decimal_places=0, max_digits=12, null=True, verbose_name='项目有效周'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='c_week_report',
            field=models.DecimalField(decimal_places=0, max_digits=12, null=True, verbose_name='周报数'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='city',
            field=models.CharField(max_length=20, null=True, verbose_name='地名'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='contract',
            field=models.CharField(max_length=20, null=True, verbose_name='客户联系人'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='contract_address',
            field=models.CharField(max_length=30, null=True, verbose_name='客户联系人地址'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='contract_phone',
            field=models.CharField(max_length=30, null=True, verbose_name='客户联系人手机'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='contract_title',
            field=models.CharField(max_length=30, null=True, verbose_name='客户联系人职务'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='cust_name',
            field=models.CharField(max_length=128, null=True, verbose_name='客户名称'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='dept',
            field=models.CharField(max_length=20, null=True, verbose_name='所属部门'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='modi_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='修改日期'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='modi_man',
            field=models.CharField(max_length=20, null=True, verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='other_memo',
            field=models.CharField(max_length=1024, null=True, verbose_name='重要情况说明'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='owner',
            field=models.CharField(max_length=20, null=True, verbose_name='所有人'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='p_do',
            field=models.CharField(max_length=30, null=True, verbose_name='财务进度'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='p_pm',
            field=models.CharField(max_length=30, null=True, verbose_name='项目经理'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='p_s_chk_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='要求验收日期'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='p_s_use_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='要求上线日期'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='p_schedule_memo',
            field=models.CharField(max_length=1024, null=True, verbose_name='合同工期要求'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='pay_memo',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='付款方式说明'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='province',
            field=models.CharField(max_length=20, null=True, verbose_name='省'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='sales',
            field=models.CharField(max_length=20, null=True, verbose_name='销售人员'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='schedule_memo',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='项目工期说明'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='task_hard_m',
            field=models.DecimalField(decimal_places=0, max_digits=12, null=True, verbose_name='合同硬件金额'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='task_m',
            field=models.DecimalField(decimal_places=0, max_digits=12, null=True, verbose_name='软件任务单金额'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='task_soft_m',
            field=models.DecimalField(decimal_places=0, max_digits=12, null=True, verbose_name='合同硬件金额'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_back_m',
            field=models.DecimalField(decimal_places=0, max_digits=12, null=True, verbose_name='已回款金额'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_back_scale',
            field=models.DecimalField(decimal_places=0, max_digits=12, null=True, verbose_name='回款比例'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_dept',
            field=models.CharField(max_length=40, null=True, verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_kind',
            field=models.CharField(max_length=40, null=True, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_m1',
            field=models.DecimalField(decimal_places=0, max_digits=12, null=True, verbose_name='首付款'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_m2',
            field=models.DecimalField(decimal_places=0, max_digits=12, null=True, verbose_name='启动款'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_m3',
            field=models.DecimalField(decimal_places=0, max_digits=12, null=True, verbose_name='上线款'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_m4',
            field=models.DecimalField(decimal_places=0, max_digits=12, null=True, verbose_name='验收款'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_m5',
            field=models.DecimalField(decimal_places=0, max_digits=12, null=True, verbose_name='质保款'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_money',
            field=models.DecimalField(decimal_places=0, max_digits=12, null=True, verbose_name='合同金额'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_month',
            field=models.CharField(default='2019/01', max_length=10, verbose_name='月份'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_org',
            field=models.CharField(max_length=40, null=True, verbose_name='大类'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_project_m',
            field=models.DecimalField(decimal_places=0, max_digits=12, null=True, verbose_name='人工差旅费'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_project_scale',
            field=models.DecimalField(decimal_places=0, max_digits=12, null=True, verbose_name='已发生费比例'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_task_m',
            field=models.DecimalField(decimal_places=0, max_digits=12, null=True, verbose_name='软件实施费'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_type',
            field=models.CharField(max_length=40, null=True, verbose_name='分项'),
        ),
    ]
