# Generated by Django 2.0.1 on 2018-12-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewproject', '0003_auto_20181213_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ewproject',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='地名'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='province',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='省'),
        ),
    ]
