# Generated by Django 2.0.1 on 2018-12-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewproject', '0004_auto_20181213_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ewproject',
            name='bargain_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='系统合同编号'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='bargain_m',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='合同总金额'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='c_budget_m',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='预算'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='c_cash_cost',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='资金成本'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='c_chk_man',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='验收参与人员'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='c_diff_m',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='预决算盈亏'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='c_file_audit_c',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='检视表要求文档数'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='c_filechklist_c',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='检视表要求文档数'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='c_final_m',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='决算'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='c_pay_cost',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='采购成本'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='c_week',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='项目有效周'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='c_week_report',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='周报数'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='contract',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='客户联系人'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='contract_address',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='客户联系人地址'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='contract_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='客户联系人手机'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='contract_title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='客户联系人职务'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='cust_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='客户名称'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='dept',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='modi_man',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='other_memo',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='重要情况说明'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='owner',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='所有人'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_back_m',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='已回款金额'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_back_scale',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='回款比例'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_dept',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_do',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='财务进度'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_kind',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_m1',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='首付款'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_m2',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='启动款'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_m3',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='上线款'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_m4',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='验收款'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_m5',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='质保款'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_money',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='合同金额'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_org',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='大类'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_pm',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='项目经理'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_project_m',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='人工差旅费'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_project_scale',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='已发生费比例'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_schedule_memo',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='合同工期要求'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_task_m',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='软件实施费'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_type',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='分项'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='sales',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='销售人员'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='task_hard_m',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='合同硬件金额'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='task_m',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='软件任务单金额'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='task_soft_m',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='合同硬件金额'),
        ),
    ]
