# Generated by Django 2.0.1 on 2018-12-13 16:39

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ewproject', '0005_auto_20181213_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ewproject',
            name='bargain_memo',
            field=DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='合同内容描述'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='c_file_memo',
            field=DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='文档检视明细'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='pay_memo',
            field=DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='付款方式说明'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='schedule_memo',
            field=DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='项目工期说明'),
        ),
    ]
