# Generated by Django 2.0.1 on 2018-12-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewproject', '0006_auto_20181213_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ewproject',
            name='bargain_m',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='合同总金额'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='c_budget_m',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='预算'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='c_cash_cost',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='资金成本'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='c_diff_m',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='预决算盈亏'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='c_file_audit_c',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='检视表要求文档数'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='c_filechklist_c',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='检视表要求文档数'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='c_final_m',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='决算'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='c_pay_cost',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='采购成本'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='c_week',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='项目有效周'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='c_week_report',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='周报数'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_back_m',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='已回款金额'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_back_scale',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='回款比例'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_m1',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='首付款'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_m2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='启动款'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_m3',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='上线款'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_m4',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='验收款'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_m5',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='质保款'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_money',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='合同金额'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_project_m',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='人工差旅费'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_project_scale',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='已发生费比例'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_task_m',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='软件实施费'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='task_hard_m',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='合同硬件金额'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='task_m',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='软件任务单金额'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='task_soft_m',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='合同硬件金额'),
        ),
    ]
