# Generated by Django 2.0.1 on 2018-12-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewproject', '0009_ewproject_p_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ewReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('typen', models.CharField(blank=True, max_length=20, null=True, verbose_name='业务类型')),
                ('builder', models.CharField(blank=True, max_length=10, null=True, verbose_name='创建人')),
                ('build_date', models.DateTimeField(blank=True, null=True, verbose_name='上传时间')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='标题')),
                ('detail', models.CharField(blank=True, max_length=128, null=True, verbose_name='内容')),
            ],
            options={
                'verbose_name': '分析报告',
                'verbose_name_plural': '分析报告',
            },
        ),
        migrations.CreateModel(
            name='ewProjectBackup',
            fields=[
            ],
            options={
                'verbose_name': '源码备份信息',
                'verbose_name_plural': '源码备份信息',
                'proxy': True,
                'indexes': [],
            },
            bases=('ewproject.ewproject',),
        ),
        migrations.CreateModel(
            name='ewProjectCheck',
            fields=[
            ],
            options={
                'verbose_name': '验收信息',
                'verbose_name_plural': '验收信息',
                'proxy': True,
                'indexes': [],
            },
            bases=('ewproject.ewproject',),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='builder_date',
            field=models.DateField(blank=True, null=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='c_chk_date',
            field=models.DateField(blank=True, null=True, verbose_name='实际验收日期'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='c_code_backup_date',
            field=models.DateField(blank=True, null=True, verbose_name='代码备份时间'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='c_database_backup_date',
            field=models.DateField(blank=True, null=True, verbose_name='数据库备份时间'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='c_file_audit_c',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='实际文档数'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='c_use_date',
            field=models.DateField(blank=True, null=True, verbose_name='实际上线日期'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='modi_date',
            field=models.DateField(blank=True, null=True, verbose_name='修改日期'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_org',
            field=models.CharField(blank=True, choices=[('营销', '营销'), ('生产', '生产'), ('城市服务', '城市服务'), ('智慧水务', '智慧水务')], max_length=40, null=True, verbose_name='大类'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_s_chk_date',
            field=models.DateField(blank=True, null=True, verbose_name='要求验收日期'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_s_use_date',
            field=models.DateField(blank=True, null=True, verbose_name='要求上线日期'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_status',
            field=models.CharField(blank=True, choices=[('已启动', '已启动'), ('已验收', '已验收'), ('取消', '取消')], max_length=40, null=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='task_soft_m',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='合同软件金额'),
        ),
    ]
