# Generated by Django 2.0.1 on 2018-12-25 10:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ewproject', '0010_auto_20181224_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('kind', models.CharField(blank=True, choices=[('源码', '源码'), ('数据库', '数据库')], max_length=40, null=True, verbose_name='类型')),
                ('builder', models.CharField(blank=True, max_length=10, null=True, verbose_name='备份人')),
                ('build_date', models.DateField(blank=True, verbose_name='备份时间')),
                ('svn', models.CharField(default='SVN', max_length=100, verbose_name='备份地点')),
            ],
            options={
                'verbose_name': '项目备份',
                'verbose_name_plural': '项目备份',
            },
        ),
        migrations.CreateModel(
            name='ProjectCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_month', models.CharField(default='2019/01', max_length=20, verbose_name='月份')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('kind', models.CharField(blank=True, choices=[('差旅', '差旅'), ('项目费用', '项目费用'), ('资金成本', '资金成本'), ('间接费', '间接费')], max_length=40, null=True, verbose_name='类型')),
                ('builder', models.CharField(blank=True, max_length=10, null=True, verbose_name='登记人')),
                ('build_date', models.DateField(blank=True, null=True, verbose_name='发生日期')),
                ('pay', models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='金额')),
            ],
            options={
                'verbose_name': '项目成本',
                'verbose_name_plural': '项目成本',
            },
        ),
        migrations.CreateModel(
            name='ProjectHrCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_month', models.CharField(default='2019/01', max_length=20, verbose_name='月份')),
                ('builder', models.CharField(blank=True, max_length=10, verbose_name='登记人')),
                ('build_date', models.DateField(blank=True, verbose_name='日期')),
                ('c1', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='工资')),
                ('c2', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='社保')),
                ('c3', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='公积金')),
                ('c4', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='其他')),
            ],
            options={
                'verbose_name': '项目人工成本',
                'verbose_name_plural': '项目人工成本',
            },
        ),
        migrations.CreateModel(
            name='ProjectPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('builder', models.CharField(blank=True, max_length=10, null=True, verbose_name='经办人')),
                ('build_date', models.DateField(blank=True, null=True, verbose_name='日期')),
                ('pay_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='申请单号')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('script', models.CharField(max_length=100, verbose_name='型号')),
                ('kind', models.CharField(blank=True, max_length=100, null=True, verbose_name='付款描述')),
                ('dept', models.CharField(blank=True, max_length=40, null=True, verbose_name='部门')),
                ('vendor', models.CharField(max_length=100, verbose_name='供应商')),
                ('qty', models.IntegerField(blank=True, default=0, null=True, verbose_name='数量')),
                ('pay', models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='总金额')),
            ],
            options={
                'verbose_name': '项目采购',
                'verbose_name_plural': '项目采购',
            },
        ),
        migrations.CreateModel(
            name='ProjectResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('download', models.FileField(upload_to='course/resource/%Y/%m', verbose_name='资源文件')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '项目资源',
                'verbose_name_plural': '项目资源',
            },
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_project_m',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='人工费'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_task_m',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='项目实施费'),
        ),
        migrations.AddField(
            model_name='projectresource',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ewproject.ewProject', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='projectpay',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ewproject.ewProject', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='projecthrcost',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ewproject.ewProject', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='projectcost',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ewproject.ewProject', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='projectbackup',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ewproject.ewProject', verbose_name='项目'),
        ),
    ]
