# Generated by Django 2.0.1 on 2018-12-26 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewproject', '0012_auto_20181225_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='ewproject',
            name='c_real_chk_date',
            field=models.DateField(blank=True, null=True, verbose_name='内部验收日期'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_status',
            field=models.CharField(blank=True, choices=[('已启动', '已启动'), ('已上线', '已上线'), ('已外验', '已外验'), ('已验收', '已验收'), ('已取消', '已取消')], max_length=40, null=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='projectbackup',
            name='build_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='备份时间'),
        ),
        migrations.AlterField(
            model_name='projectcost',
            name='build_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='发生日期'),
        ),
        migrations.AlterField(
            model_name='projecthrcost',
            name='build_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='projectpay',
            name='build_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='projectreceived',
            name='build_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='发生日期'),
        ),
    ]
