# Generated by Django 2.0.1 on 2018-12-27 17:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ewproject', '0013_auto_20181226_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='变更内容')),
                ('kind', models.CharField(blank=True, max_length=40, null=True, verbose_name='类型')),
                ('c_date', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='变更时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ewproject.ewProject', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目重要变更',
                'verbose_name_plural': '项目重要变更',
            },
        ),
    ]
