# Generated by Django 2.0.1 on 2019-03-13 20:35

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewproject', '0015_auto_20190107_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectbackup',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectcost',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projecthrcost',
            name='project',
        ),
        migrations.DeleteModel(
            name='ewProjectBackup',
        ),
        migrations.RenameField(
            model_name='ewproject',
            old_name='c_pay_cost',
            new_name='p_pay',
        ),
        migrations.RemoveField(
            model_name='ewproject',
            name='bargain_id',
        ),
        migrations.RemoveField(
            model_name='ewproject',
            name='c_chk_date',
        ),
        migrations.RemoveField(
            model_name='ewproject',
            name='c_chk_man',
        ),
        migrations.RemoveField(
            model_name='ewproject',
            name='c_code_backup_date',
        ),
        migrations.RemoveField(
            model_name='ewproject',
            name='c_database_backup_date',
        ),
        migrations.RemoveField(
            model_name='ewproject',
            name='c_file_audit_c',
        ),
        migrations.RemoveField(
            model_name='ewproject',
            name='c_use_date',
        ),
        migrations.RemoveField(
            model_name='ewproject',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='ewproject',
            name='contract_address',
        ),
        migrations.RemoveField(
            model_name='ewproject',
            name='contract_phone',
        ),
        migrations.RemoveField(
            model_name='ewproject',
            name='contract_title',
        ),
        migrations.RemoveField(
            model_name='ewproject',
            name='cust_name',
        ),
        migrations.RemoveField(
            model_name='ewproject',
            name='modi_date',
        ),
        migrations.RemoveField(
            model_name='ewproject',
            name='modi_man',
        ),
        migrations.RemoveField(
            model_name='ewproject',
            name='other_memo',
        ),
        migrations.RemoveField(
            model_name='ewproject',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='ewproject',
            name='p_do',
        ),
        migrations.RemoveField(
            model_name='ewproject',
            name='p_m1',
        ),
        migrations.RemoveField(
            model_name='ewproject',
            name='p_m2',
        ),
        migrations.RemoveField(
            model_name='ewproject',
            name='p_m3',
        ),
        migrations.RemoveField(
            model_name='ewproject',
            name='p_m4',
        ),
        migrations.RemoveField(
            model_name='ewproject',
            name='p_m5',
        ),
        migrations.RemoveField(
            model_name='ewproject',
            name='p_money',
        ),
        migrations.RemoveField(
            model_name='ewproject',
            name='p_project_m',
        ),
        migrations.RemoveField(
            model_name='ewproject',
            name='p_task_m',
        ),
        migrations.AddField(
            model_name='ewproject',
            name='c_code_backup_c',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='源码备份'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='c_code_backup_s',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='源码备份评分'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='c_cost_s',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='费用评分'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='c_data_backup_c',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='数据库备份'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='c_data_backup_s',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='数据库备份评分'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='c_date',
            field=models.DateField(blank=True, null=True, verbose_name='评分日期'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='c_delay_m',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='延期月份'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='c_file_s',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='文档评分'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='c_filechklist_s',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='检视表评分'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='c_filelist_memo',
            field=DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='文档检视明细'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='c_jh_c',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='计划'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='c_jh_s',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='计划评分'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='c_jj_c',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='维护交接作业书'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='c_jj_s',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='交接评分'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='c_js_c',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='决算'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='c_js_s',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='决算评分'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='c_m_pay',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='当月采购成本'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='c_m_project',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='当月项目成本'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='c_m_total',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='当月采购成本'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='c_sched_s',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='工期评分'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='c_total_s',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='总分'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='c_week_s',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='周报评分'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='c_ys_c',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='预算'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='c_ys_s',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='预算评分'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='c_ysb_c',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='验收报告'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='c_ysb_s',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='验收报告评分'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='p_begin_date',
            field=models.DateField(blank=True, null=True, verbose_name='计划开始日期'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='p_profit',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='成本合计'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='p_project',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='项目成本'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='p_total',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='成本合计'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='builder_date',
            field=models.DateField(blank=True, null=True, verbose_name='立项日期'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='c_file_memo',
            field=DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='c_filechklist_c',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='检视表'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='c_real_chk_date',
            field=models.DateField(blank=True, null=True, verbose_name='结案时间'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='dept',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='销售部门'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_project_scale',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='已发生比例'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_s_chk_date',
            field=models.DateField(blank=True, null=True, verbose_name='计划验收日期'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_s_use_date',
            field=models.DateField(blank=True, null=True, verbose_name='计划完成日期'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_status',
            field=models.CharField(blank=True, choices=[('在建', '在建'), ('已结案', '已结案'), ('结算', '结算'), ('取消', '取消')], max_length=40, null=True, verbose_name='类型'),
        ),
        migrations.DeleteModel(
            name='ProjectBackup',
        ),
        migrations.DeleteModel(
            name='ProjectCost',
        ),
        migrations.DeleteModel(
            name='ProjectHrCost',
        ),
    ]
