# Generated by Django 2.0.1 on 2019-03-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewproject', '0016_auto_20190313_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectchange',
            name='new',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='现值'),
        ),
        migrations.AddField(
            model_name='projectchange',
            name='old',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='原值'),
        ),
    ]
