# Generated by Django 2.0.1 on 2019-03-15 09:21

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewproject', '0017_auto_20190314_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='ewproject',
            name='p_budget_memo',
            field=DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='预算概要'),
        ),
        migrations.AddField(
            model_name='ewproject',
            name='p_plan_memo',
            field=DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='里程碑信息'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='c_m_total',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='当月总成本'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_back_scale',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='回款比例%'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_profit',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='盈利'),
        ),
        migrations.AlterField(
            model_name='ewproject',
            name='p_project_scale',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='已发生比例%'),
        ),
    ]
