# Generated by Django 2.0.1 on 2018-08-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20180812_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('fa', '解决方案'), ('zs', '在售产品'), ('ts', '停售产品')], default='zs', max_length=20, verbose_name='课程类别'),
        ),
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('A', 'A新兵营'), ('B', 'B十八般兵器'), ('C', 'C货好不难卖'), ('D', 'D武功密籍'), ('E', 'E江湖风云录')], max_length=2, verbose_name='难度'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher_tell',
            field=models.CharField(default='', max_length=300, verbose_name='课程重要性'),
        ),
        migrations.AlterField(
            model_name='course',
            name='you_need_know',
            field=models.CharField(default='', max_length=300, verbose_name='课程定位'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(default='http://blog.ewide.net/', max_length=200, verbose_name='访问地址'),
        ),
    ]
