# Generated by Django 2.0.1 on 2018-08-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20180822_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('A', '易'), ('B', '中'), ('C', '难')], max_length=2, verbose_name='难度'),
        ),
    ]
