# Generated by Django 2.0.1 on 2018-08-24 16:45

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20180824_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='detail',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='章节正文'),
        ),
    ]
