# Generated by Django 2.0.1 on 2018-08-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20180824_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCourse',
            fields=[
            ],
            options={
                'verbose_name': '我发的课程',
                'verbose_name_plural': '我发的课程',
                'proxy': True,
                'indexes': [],
            },
            bases=('courses.course',),
        ),
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('A', '初级'), ('B', '中级'), ('C', '高级')], max_length=2, verbose_name='难度'),
        ),
    ]
