# Generated by Django 2.0.1 on 2018-08-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20180829_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='email',
            field=models.EmailField(default='1@ewide.net', max_length=50, verbose_name='邮箱'),
        ),
    ]
