# Generated by Django 2.0.1 on 2018-08-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20180829_2043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['name'], 'verbose_name': '章节', 'verbose_name_plural': '章节'},
        ),
        migrations.AlterField(
            model_name='course',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='编辑邮箱'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tag',
            field=models.CharField(default='', max_length=15, verbose_name='推荐类型标签'),
        ),
    ]
