# Generated by Django 2.0.1 on 2018-08-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20180829_2139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-add_time'], 'verbose_name': '课程', 'verbose_name_plural': '课程'},
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('fa', '解决方案'), ('zs', '在售产品'), ('ts', '停售产品'), ('ys', '预售产品')], default='zs', max_length=20, verbose_name='课程类别'),
        ),
    ]
