# Generated by Django 2.0.1 on 2019-07-19 18:37

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='xxProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_month', models.CharField(default='2019/01', max_length=10, verbose_name='消息月份')),
                ('p_date', models.DateField(blank=True, null=True, verbose_name='任务单时间')),
                ('province', models.CharField(blank=True, max_length=20, null=True, verbose_name='省')),
                ('city', models.CharField(blank=True, max_length=20, null=True, verbose_name='地名')),
                ('area_rank', models.CharField(blank=True, default='市', max_length=20, null=True, verbose_name='级别')),
                ('name', models.CharField(max_length=128, verbose_name='项目名称')),
                ('budget_m', models.IntegerField(blank=True, default=0, null=True, verbose_name='预计金额')),
                ('xxsales', models.CharField(blank=True, max_length=20, null=True, verbose_name='新兴销售人员')),
                ('EWsales', models.CharField(blank=True, max_length=20, null=True, verbose_name='易维对接人')),
                ('p_org', models.CharField(blank=True, choices=[('营销', '营销'), ('生产', '生产'), ('城市服务', '城市服务'), ('智慧水务', '智慧水务')], max_length=40, null=True, verbose_name='大类')),
                ('p_stage', models.CharField(blank=True, choices=[('设想', '设想'), ('立项', '立项'), ('招采', '招采'), ('施工', '施工'), ('暂停', '暂停'), ('取消', '取消')], max_length=40, null=True, verbose_name='阶段')),
                ('total_pr', models.IntegerField(blank=True, default=0, null=True, verbose_name='概率')),
                ('start_cond', models.CharField(max_length=128, verbose_name='启动前置条件')),
                ('start_month', models.DateField(blank=True, null=True, verbose_name='计划开始日期')),
                ('p_memo', DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='项目信息')),
                ('finish_memo', DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='已完成工作')),
                ('next_memo', DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='下一步工作')),
            ],
            options={
                'verbose_name': '聚联项目',
                'verbose_name_plural': '聚联项目',
            },
        ),
        migrations.CreateModel(
            name='xxProjectChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='变更内容')),
                ('kind', models.CharField(blank=True, max_length=40, null=True, verbose_name='类型')),
                ('old', models.CharField(blank=True, max_length=40, null=True, verbose_name='原值')),
                ('new', models.CharField(blank=True, max_length=40, null=True, verbose_name='现值')),
                ('c_date', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='变更时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xxproject.xxProject', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目重要变更',
                'verbose_name_plural': '项目重要变更',
            },
        ),
        migrations.CreateModel(
            name='xxProjectResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('download', models.FileField(upload_to='course/resource/%Y/%m', verbose_name='资源文件')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xxproject.xxProject', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目资源',
                'verbose_name_plural': '项目资源',
            },
        ),
    ]
