# Generated by Django 2.0.1 on 2019-08-08 11:33

import DjangoUeditor.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xxproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='xxProjectComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pl', '好评'), ('cp', '差评'), ('zx', '咨询'), ('jl', '交流')], default='pl', max_length=2, verbose_name='类型')),
                ('ctitle', models.CharField(default='交流', max_length=30, verbose_name='主题')),
                ('comments', DjangoUeditor.models.UEditorField(verbose_name='交流')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='交流时间')),
            ],
            options={
                'verbose_name': '项目交流',
                'verbose_name_plural': '项目交流',
            },
        ),
        migrations.AlterField(
            model_name='xxproject',
            name='p_org',
            field=models.CharField(blank=True, choices=[('产销差', '产销差'), ('智慧水务', '智慧水务'), ('三供一业', '三供一业'), ('营销', '营销'), ('供水', '供水'), ('水利', '水利'), ('排水', '排水'), ('服务', '服务')], max_length=40, null=True, verbose_name='大类'),
        ),
        migrations.AlterField(
            model_name='xxproject',
            name='start_cond',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='启动前置条件'),
        ),
        migrations.AddField(
            model_name='xxprojectcomments',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xxproject.xxProject', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='xxprojectcomments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
