# Generated by Django 2.0.1 on 2019-11-21 18:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xxproject', '0002_auto_20190808_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='xxProjectB',
            fields=[
            ],
            options={
                'verbose_name': '聚联项目手机浏览',
                'verbose_name_plural': '聚联项目手机浏览',
                'proxy': True,
                'indexes': [],
            },
            bases=('xxproject.xxproject',),
        ),
        migrations.AlterModelOptions(
            name='xxproject',
            options={'verbose_name': '聚联项目清单', 'verbose_name_plural': '聚联项目清单'},
        ),
        migrations.AlterField(
            model_name='xxprojectcomments',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='xxprojectcomments',
            name='kind',
            field=models.CharField(choices=[('pl', '评论'), ('rw', '任务'), ('zx', '咨询'), ('jl', '建议')], default='pl', max_length=2, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='xxprojectcomments',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
