# Generated by Django 2.0.1 on 2018-10-12 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181010_1442'),
        ('users', '0006_auto_20180917_1135'),
    ]

    operations = [
    ]
