# Generated by Django 2.0.1 on 2019-12-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gis_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_id', models.CharField(max_length=100, verbose_name='项目')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('p_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='类型')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='经度')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='纬度')),
            ],
            options={
                'verbose_name': '地图信息',
                'verbose_name_plural': '地图信息',
            },
        ),
        migrations.DeleteModel(
            name='address_info',
        ),
    ]
