# Generated by Django 2.0.1 on 2019-12-27 12:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='scenhtml',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('typen', models.CharField(blank=True, choices=[('水务', '水务'), ('水利', '水利')], max_length=30, null=True, verbose_name='场景类型')),
                ('builder', models.CharField(blank=True, max_length=10, null=True, verbose_name='创建人')),
                ('build_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='上传时间')),
                ('download', models.FileField(upload_to='course/resource/%Y/%m', verbose_name='应用场景')),
            ],
            options={
                'verbose_name': '应用场景',
                'verbose_name_plural': '应用场景',
            },
        ),
        migrations.CreateModel(
            name='scenResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('download', models.FileField(upload_to='course/resource/%Y/%m', verbose_name='资源文件')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scen.scenhtml', verbose_name='场景')),
            ],
            options={
                'verbose_name': '场景附件',
                'verbose_name_plural': '场景附件',
            },
        ),
    ]
