# Generated by Django 2.0.1 on 2018-08-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ewsales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('owner', models.CharField(blank=True, max_length=20, null=True, verbose_name='所有人')),
                ('typen', models.CharField(blank=True, max_length=20, null=True, verbose_name='业务类型')),
                ('builder', models.CharField(blank=True, max_length=10, null=True, verbose_name='创建人')),
                ('builder_date', models.DateTimeField(blank=True, null=True, verbose_name='签约日期')),
                ('dept', models.CharField(blank=True, max_length=40, null=True, verbose_name='所属部门')),
                ('province', models.CharField(blank=True, max_length=20, null=True, verbose_name='省份')),
                ('city', models.CharField(blank=True, max_length=20, null=True, verbose_name='城市')),
                ('prj_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='客户名')),
                ('status', models.CharField(blank=True, max_length=30, null=True, verbose_name='完成状态')),
                ('order_m', models.FloatField(blank=0, null=True, verbose_name='金额')),
            ],
            options={
                'verbose_name': '销售合同',
                'verbose_name_plural': '销售合同',
            },
        ),
    ]
