# Generated by Django 2.0.1 on 2018-08-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myechart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ewsales',
            name='attachfile',
            field=models.FileField(default='', upload_to='upload'),
        ),
        migrations.AlterField(
            model_name='ewsales',
            name='order_m',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金额'),
        ),
    ]
