# Generated by Django 2.0.1 on 2019-02-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myechart', '0002_auto_20180818_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='wxmsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(blank=True, default=0, null=True, verbose_name='优先级别')),
                ('to_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='发送类型')),
                ('to_man', models.CharField(blank=True, max_length=40, null=True, verbose_name='责任人')),
                ('builder', models.CharField(blank=True, max_length=20, null=True, verbose_name='创建人')),
                ('builder_date', models.DateTimeField(blank=True, null=True, verbose_name='创建日期')),
                ('msg', models.CharField(blank=True, max_length=1024, null=True, verbose_name='内容')),
                ('send_flag', models.IntegerField(blank=True, default=0, null=True, verbose_name='发出标志')),
                ('ans_status', models.IntegerField(blank=True, default=0, null=True, verbose_name='回复标志')),
                ('effect_b', models.DateTimeField(blank=True, null=True, verbose_name='生效起始时间')),
                ('effect_e', models.DateTimeField(blank=True, null=True, verbose_name='生效截止时间')),
                ('area', models.CharField(blank=True, max_length=20, null=True, verbose_name='发送范围类型')),
            ],
            options={
                'verbose_name': '微信自动任务',
                'verbose_name_plural': '微信自动任务',
            },
        ),
    ]
