# Generated by Django 2.0.1 on 2019-12-11 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='submsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='消息名称')),
                ('topic', models.CharField(blank=True, max_length=64, null=True, verbose_name='主题')),
                ('subtime', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='消息时间')),
                ('payload', models.CharField(blank=True, max_length=500, null=True, verbose_name='消息内容')),
            ],
            options={
                'verbose_name': 'MQTT消息明细',
                'verbose_name_plural': 'MQTT消息明细',
            },
        ),
    ]
