# Generated by Django 2.0.1 on 2019-12-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submsg',
            name='payload',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='消息内容'),
        ),
    ]
