# Generated by Django 2.0.1 on 2019-12-07 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submsg',
            name='payload',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='消息内容'),
        ),
        migrations.AlterField(
            model_name='submsg',
            name='subtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='消息时间'),
        ),
    ]
