# Generated by Django 2.0.1 on 2019-12-27 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0002_auto_20191207_2156'),
        ('mqtt', '0002_auto_20191211_1043'),
    ]

    operations = [
    ]
